In [1]:
import numpy as np
import pandas as pd

In [2]:
def import_data(file_path):
    data = pd.read_csv(file_path)
    A = data.iloc[:,:-1].values
    b = data.iloc[:,-1].values
    return A,b

In [4]:
filename = 'data1.csv'
A,b = import_data(filename)
print('Matrix A: ')
print(A)
print('Vector b: ')
print(b)

Matrix A: 
[[77 85]
 [40 49]
 [51 55]
 [80 71]
 [22 62]
 [52 73]
 [89 55]
 [59 69]
 [70 12]
 [44 98]
 [38 51]
 [22 98]
 [98 52]
 [16 60]
 [47 96]
 [15 87]
 [37 39]
 [15 64]
 [41 28]
 [77 12]
 [18 67]
 [14 48]
 [76 27]
 [56 61]
 [34 32]
 [63 55]
 [35 42]
 [76 14]
 [26 34]
 [69 28]
 [24 15]
 [92 40]
 [59 53]
 [33 91]
 [63 84]
 [84 86]
 [57 87]
 [78 32]
 [36 22]
 [91 48]
 [67 80]
 [95 23]
 [92 72]
 [73 99]
 [92 48]
 [94 53]
 [13 60]
 [76 27]
 [10 54]
 [36 70]
 [86 24]
 [70 52]
 [89 15]
 [76 77]
 [90 57]
 [46 83]
 [15 10]
 [61 93]
 [88 44]
 [57 53]
 [33 82]
 [58 22]
 [12 65]
 [85 40]
 [28 14]
 [48 42]
 [95 45]
 [43 70]
 [99 89]
 [30 18]
 [17 49]
 [74 37]
 [15 26]
 [85 63]
 [35 36]
 [33 43]
 [85 94]
 [28 20]
 [17 11]
 [15 43]
 [46 55]
 [25 48]
 [61 22]
 [33 26]
 [78 67]
 [45 37]
 [80 38]
 [29 11]
 [20 63]
 [27 39]
 [79 57]
 [63 77]
 [54 31]
 [64 22]
 [86 47]
 [79 75]
 [15 58]
 [20 57]
 [80 37]]
Vector b: 
[ 89.6  56.3  55.8  75.7  56.   67.7  71.2  71.   34.4  90.8  52.1  85.2
  68.8  52.8 

## QR Factorization

In [5]:
def qr_factorization(A):
    # Get the number of rows (m) and columns (n) of A
    m, n = A.shape

    # Initialize Q and R matrices
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    # Gram-Schmidt process
    for j in range(n):
        # Start with the current column of A
        v = A[:, j]

        # Subtract the projection of v onto each previous Q column
        for i in range(j):
            # Calculate the projection coefficient (dot product)
            R[i, j] = np.dot(Q[:, i].T, A[:, j])

            # Subtract the projection from v
            v = v - R[i, j] * Q[:, i]

        # The j-th diagonal element of R is the norm of the orthogonalized vector v
        R[j, j] = np.linalg.norm(v)

        # Normalize the orthogonalized vector to create the j-th column of Q
        Q[:, j] = v / R[j, j]

    return Q, R


In [6]:
Q, R = qr_factorization(A)
print("Q:")
print(Q)
print("R:")
print(R)

Q:
[[ 0.12878685  0.08003763]
 [ 0.06690226  0.05662035]
 [ 0.08530038  0.04897913]
 [ 0.13380452  0.0293987 ]
 [ 0.03679624  0.13998051]
 [ 0.08697294  0.10248536]
 [ 0.14885753 -0.04178134]
 [ 0.09868084  0.07334529]
 [ 0.11707896 -0.12992724]
 [ 0.07359249  0.1992243 ]
 [ 0.06355715  0.06760773]
 [ 0.03679624  0.25176983]
 [ 0.16391054 -0.07259302]
 [ 0.0267609   0.1481006 ]
 [ 0.07861016  0.18584848]
 [ 0.02508835  0.23433102]
 [ 0.06188459  0.03273306]
 [ 0.02508835  0.16291007]
 [ 0.06857482 -0.01097852]
 [ 0.12878685 -0.14664627]
 [ 0.03010602  0.16506054]
 [ 0.02341579  0.11561436]
 [ 0.1271143  -0.09767896]
 [ 0.09366317  0.05566852]
 [ 0.05686692  0.01816155]
 [ 0.10537106  0.02031793]
 [ 0.05853948  0.0468257 ]
 [ 0.1271143  -0.13804732]
 [ 0.04348647  0.04347953]
 [ 0.1154064  -0.07785466]
 [ 0.04014136 -0.01074352]
 [ 0.1538752  -0.09552553]
 [ 0.09868084  0.02366115]
 [ 0.05519437  0.20376025]
 [ 0.10537106  0.11037044]
 [ 0.14049475  0.06642385]
 [ 0.09533572  0.13401681

In [7]:
def reconstruct_A(Q, R):
    return np.dot(Q, R)

In [8]:
reconstructed_A = reconstruct_A(Q, R)
print("Reconstructed A:")
print(reconstructed_A)

Reconstructed A:
[[77. 85.]
 [40. 49.]
 [51. 55.]
 [80. 71.]
 [22. 62.]
 [52. 73.]
 [89. 55.]
 [59. 69.]
 [70. 12.]
 [44. 98.]
 [38. 51.]
 [22. 98.]
 [98. 52.]
 [16. 60.]
 [47. 96.]
 [15. 87.]
 [37. 39.]
 [15. 64.]
 [41. 28.]
 [77. 12.]
 [18. 67.]
 [14. 48.]
 [76. 27.]
 [56. 61.]
 [34. 32.]
 [63. 55.]
 [35. 42.]
 [76. 14.]
 [26. 34.]
 [69. 28.]
 [24. 15.]
 [92. 40.]
 [59. 53.]
 [33. 91.]
 [63. 84.]
 [84. 86.]
 [57. 87.]
 [78. 32.]
 [36. 22.]
 [91. 48.]
 [67. 80.]
 [95. 23.]
 [92. 72.]
 [73. 99.]
 [92. 48.]
 [94. 53.]
 [13. 60.]
 [76. 27.]
 [10. 54.]
 [36. 70.]
 [86. 24.]
 [70. 52.]
 [89. 15.]
 [76. 77.]
 [90. 57.]
 [46. 83.]
 [15. 10.]
 [61. 93.]
 [88. 44.]
 [57. 53.]
 [33. 82.]
 [58. 22.]
 [12. 65.]
 [85. 40.]
 [28. 14.]
 [48. 42.]
 [95. 45.]
 [43. 70.]
 [99. 89.]
 [30. 18.]
 [17. 49.]
 [74. 37.]
 [15. 26.]
 [85. 63.]
 [35. 36.]
 [33. 43.]
 [85. 94.]
 [28. 20.]
 [17. 11.]
 [15. 43.]
 [46. 55.]
 [25. 48.]
 [61. 22.]
 [33. 26.]
 [78. 67.]
 [45. 37.]
 [80. 38.]
 [29. 11.]
 [20. 63.]
 [27

In [9]:
def find_x(Q, R, b):
    Q_T_b = np.dot(Q.T, b)
    x = np.linalg.solve(R, Q_T_b)
    return x

In [10]:
x = find_x(Q, R, b)
print("Value of x:")
print(x)

Value of x:
[0.34441961 0.75280002]


In [11]:
def find_b_prime(A, x):
    return np.dot(A, x)

In [12]:
b_prime = find_b_prime(A, x)
print("Value of b':")
print(b_prime)

Value of b':
[ 90.50831197  50.66398556  58.96940141  81.00237047  54.2508329
  72.86422145  72.05734657  72.26395862  33.14297296  88.92886517
  51.48074639  81.35163376  72.89872298  50.67871519  88.45652395
  70.65989623  42.10272649  53.34549568  35.19960466  35.55391023
  56.63715458  40.95627568  46.50149097  65.2082996   35.79986749
  63.10243672  43.67228734  36.71509066  34.55011066  44.84335373
  19.55807099  61.79860504  60.21915823  79.87064929  84.93363741
  93.67204926  85.12551983  50.95433031  28.96070647  67.47658562
  83.30011576  50.03426346  85.88820581  99.66983387  67.82100523
  72.27384457  49.64545636  46.50149097  44.09539739  65.09510762
  47.687287    63.25497392  41.94534561  84.14149217  73.90736623
  78.32570403  12.69429438  91.01999841  63.4321267   59.53031901
  73.09544908  36.53793788  53.06503687  59.38766777  20.1829494
  48.14974227  66.59586399  67.50604489 101.09674348  23.88298872
  42.74233454  53.34065199  24.73909477  76.70206832  39.1554872


In [13]:
def calculate_loss(a, x, b):
    b_prime = np.dot(a, x)
    mse = np.mean((b - b_prime) ** 2)
    return mse

In [14]:
final_loss = calculate_loss(A, x, b)
print(f"Final loss: {final_loss:.6f}")

Final loss: 10.366433


In [15]:
import time

def compute_qr_factorization_time(A):
    start_time = time.time()

    # Perform QR factorization
    Q, R = qr_factorization(A)

    end_time = time.time()

    # Only return the time taken; do not print here
    return end_time - start_time


In [16]:
# Compute the time taken for gradient descent
time_taken = compute_qr_factorization_time(A)
print(f"Time taken for QR factorisation: {time_taken:.6f} seconds")

Time taken for QR factorisation: 0.001026 seconds
